name: Windows Build Signing Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch: # Allow manual trigger

jobs:
  sign:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run the action
        uses: peculiarventures/goodkey-win-signtool-action@v1.1.0
        with:
          organization: "a3dac85b-0df1-48e0-8fa6-9d8b3a2cb837"
          token: ${{ secrets.CLI_SIGNING_ACCESS_TOKEN }}
          certificate: "224b501264c1454d4627268297670451aed3b0d9"
          file: "fixtures/sample-build.exe"
          timestamp_rfc3161_url: "http://timestamp.digicert.com"
          timestamp_digest_algorithm: "sha256"
          description: "This is a test file"
          description_url: "https://example.com"
          file_digest_algorithm: "sha256"
